//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDD_SCREENDLG                   103
#define IDI_ICON_APP                    103
#define IDD_STARTUP                     103
#define IDB_STARTUP                     107
#define IDB_10                          112
#define IDB_14                          113
#define IDB_15                          114
#define IDB_16                          115
#define IDB_17                          116
#define IDB_18                          117
#define IDB_19                          118
#define IDB_20                          119
#define IDB_21                          120
#define IDB_22                          121
#define IDB_23                          122
#define IDG_07                          123
#define IDB_05                          125
#define IDB_25                          127
#define IDB_13                          128
#define IDB_08                          130
#define IDB_06                          131
#define IDB_01                          133
#define IDB_11                          134
#define IDB_02                          135
#define IDB_12                          136
#define IDB_03                          137
#define IDB_27                          138
#define IDB_24                          139
#define IDB_26                          140
#define IDR_SOUND_TIR                   141
#define IDR_SOUND_EXPLOSION             152
#define IDR_SOUND_APPLAUSE              153
#define IDR_SOUND_DESCENTE              154
#define IDR_SOUND_XM                    156
#define IDR_BINARY_FMOD                 159
#define IDR_BINARY_FONT_TGA             160
#define IDC_CURSOR_CROSS                166
#define IDB_LOADING                     169
#define IDB_PARTICLE                    171
#define IDJ_28                          187
#define IDB_30                          194
#define IDJ_37                          195
#define IDJ_38                          196
#define IDR_SOUND_TIR3D                 198
#define IDB_39                          199
#define IDJ_S02_5121                    202
#define IDJ_SPHERE_O                    203
#define IDR_BINARY_PLAYER_3DS           204
#define IDR_BINARY_SHIP_3DS             205
#define IDR_BINARY_SPHERE_OGIVE_3DS     206
#define IDJ_F02_512                     209
#define IDR_BINARY_SUPERSHIP_3DS        210
#define IDJ_42                          216
#define IDG_43                          217
#define IDR_SOUND_SHIELD_CHARGE         218
#define IDJ_44                          220
#define IDT_00                          225
#define IDT_04                          232
#define IDT_40                          233
#define IDB_STARTUP_INTERNET            235
#define IDD_DIALOG_ABOUT                236
#define IDD_ABOUT                       236
#define IDR_README_TXT                  240
#define IDB_STARTUP_INTERNET_OVER       242
#define IDR_SOUND_XM_ABOUT              244
#define IDB_BUTTON_MUTE                 246
#define IDB_BUTTON_PLAY                 247
#define IDG_35                          264
#define IDG_36                          271
#define IDC_CURSOR_HAND                 274
#define IDC_CURSOR_HAND_CLOSED          275
#define IDJ_CADRE_CENTRE                278
#define IDJ_CADRE_CONTOUR               279
#define IDJ_CADRE_CENTRE_LONG           279
#define IDJ_09                          280
#define IDJ_41                          281
#define IDR_BINARY_FIGHTER_LASER_3DS    282
#define IDJ_31                          283
#define IDJ_32                          284
#define IDJ_45                          285
#define IDG_46                          286
#define IDR_SOUND_BONUS                 287
#define IDG_47                          288
#define IDR_SOUND_KEY                   289
#define IDR_BINARY_MISSILE_3DS          291
#define IDD_MESSAGEBOX                  302
#define IDD_STREAMING                   302
#define IDI_ICON1                       304
#define IDI_ICON_MUSIC                  306
#define IDR_SOUND_CROSS                 307
#define IDP_48                          312
#define IDP_49                          313
#define IDP_35                          314
#define IDP_50                          315
#define IDP_51                          316
#define IDG_52                          317
#define IDJ_53                          318
#define IDR_README_ES_TXT               319
#define IDR_README_FR_TXT               320
#define IDB_SRARTUP_NVIDIA              331
#define IDB_STARTUP_NVIDIA              331
#define IDC_640_480                     1001
#define IDC_800_600                     1002
#define IDC_1024_768                    1003
#define IDC_16BPP                       1004
#define IDC_32BPP                       1006
#define IDC_FULLSCREEN                  1007
#define IDC_QUICK_FULLSCREEN            1008
#define IDC_MIPMAP                      1011
#define IDC_WINDOW                      1015
#define IDC_VSYNC                       1017
#define IDC_BILLBOARDING                1018
#define IDC_ANTI_ALIASING               1019
#define IDC_STREAM                      1020
#define IDC_BUTTON_CLOSE                1030
#define IDC_BUTTON_ABOUT                1031
#define IDC_BUTTON_MUTE                 1033
#define IDC_HOMEPAGE                    1038
#define IDC_MAIL                        1039
#define IDC_GNU_GPL                     1041
#define IDC_BITRATE                     1046
#define IDC_SLIDER_WIVIK                1054
#define IDC_TEXT_WIVIK                  1055
#define IDC_CHECK1                      1056
#define IDC_CHECK_WIVIK                 1056
#define IDC_MESSAGE                     1057
#define IDC_STATIC_CUSTOM1              1057
#define IDC_STREAMING_URL               1058
#define IDC_STREAMING_SITE              1059
#define IDC_STATIC_DISPLAY              1063
#define IDC_STATIC_MISC                 1064
#define IDC_STATIC_QUALITY              1065
#define IDC_STATIC_HOMEPAGE             1066
#define IDC_STATIC_FORUM                1067
#define IDC_STATIC_CUSTOM2              1068
#define IDC_BUTTON1                     1074
#define IDC_ANTI_ALIASING_MODE_bak      1074
#define IDC_STATIC_VERSION              1075
#define IDC_ANTI_ALIASING_MODE          1076

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
